### PR TITLE
add new app icons

### PR DESCRIPTION
**Pull request by allaeddineomc**
Pasted image

### CODE REVIEW

**Comment by eminfedar** [comment]
Very nice icon! Did you design it yourself (asking for license purposes)?

Additionally, green is kinda the primary color of this application so how about something like this?

vaktisalah-icon-refactor

**Comment by allaeddineomc** [comment]
yes i designed it myself and the licensing is up to you 
i don't think it's a good idea to make parts of the icon green and keeping the yellow around , i also think it's not necessary for the icon to follow the accent color of the ui since it won't be displayed inside the app ui  
also i'm not sure if the concept of project defined accent colors in gnome apps is gonna last for long since user defined accent colors should be coming to vanilla gnome soon

**Comment by eminfedar** [comment]
Ok so I approve this PR then. It is already nice. 👍🏻

I thought it would look like the qubba of the masjid al-nabawi too so. 
image

**Comment by allaeddineomc** [comment]
g857
what do you think of this one ? this is as close as i could get to the original colors without breaking gnome's color palette.
personally i think the original one looks nicer

**Comment by eminfedar** [comment]
Original is good  :) Thanks for your efforts!

**Pull request merged**
